### ISSUE TITLE
Affected matrix generation fail with: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by tamascsaba** [e-square-io/nx-github-actions#53]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Affected matrix generation fail with:
```
>  NX   Cannot read properties of undefined (reading 'endsWith')
```

## Minimal reproduction of the problem with instructions

I had to add `NX_WORKSPACE_ROOT_PATH`, because `workingDirectory` is not working.
My configuration looks like:
```
  setup:
    runs-on: ubuntu-latest
    name: Affected Matrix
    env:
      NX_VERBOSE_LOGGING: true
      NX_WORKSPACE_ROOT_PATH: ${{ github.workspace }}/nx-root/
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Calculate affected projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          debug: true
          targets: 'test,build'
          maxDistribution: 1
          args: ''
```

## Environment

<pre><code>
- Nx version: 14.4.2 
- Node version: XX  
- Platform:  Linux
</code></pre>

**Comment by tamascsaba** [comment]
@robinpellegrims thank you very much your response in advance 👍

**Comment by ronnetzer** [comment]
Hi @tamascsaba,

Thank you for reporting the issue,
1. Please create a repo that reproduces the issue so we'll be able to debug the fix
2. "I had to add NX_WORKSPACE_ROOT_PATH, because workingDirectory is not working."
I didn't understand if it solved the issue? or without `NX_WORKSPACE_ROOT_PATH` you get a different error?

**Comment by robinpellegrims** [comment]
I'm having the same issue after converting all projects to use separate project.json files instead of the global workspace.json. Might be related to this library still using nx v13? Can we update the nx packages to v14?

**Comment by tamascsaba** [comment]
Sorry for the late response, but I haven't had time to create an example repository, but maybe I can give you a general description of our project.
1. We use `"version": 2,` format with lot of  buildable libraries and several apps, the main project file is the `angular.json`
2. Without `NX_WORKSPACE_ROOT_PATH` I got an error about missing `nx.json` file.

**Comment by ronnetzer** [comment]
@robinpellegrims Thanks for reporting,
I have several projects with the new `project.json` files format that works just fine with NX 14 so I'm not sure this is the problem.
In order to proceed I'll need some minimal reproduction of this issue

@tamascsaba Regarding your 2nd point, do you mind opening it in a separate issue? its unrelated to this one

**Comment by robinpellegrims** [comment]
I created a minimal reproduction repository [here](https://github.com/robinpellegrims/nx-github-actions-error).

It's a fresh nx repository created using `npx create-nx-workspace@latest` with the `angular-nest` preset. Afterwards I copied the default `e-square-io/nx-affected-matrix` workflow configuration from the README.

I hope this helps, let me know if you need anything else.

**Comment by tamascsaba** [comment]
I opened a separate issue: https://github.com/e-square-io/nx-github-actions/issues/56 as well.

**Comment by jason-edstrom** [comment]
I am having this exact issue with a react-native monorepo that has 9 apps already in place.  I have been trying to understand what I'm missing.

**Comment by jason-edstrom** [comment]
@robinpellegrims @ronnetzer 
Repro-Repo here: https://github.com/jason-edstrom/nx-affected-bug-repo

**Comment by ronnetzer** [comment]
Apparently this is something in NX, https://github.com/nrwl/nx/issues/8968
it was probably fixed in NX 14 but since the actions use 13 and the workspace was generated by 14 we get this error.

as a workaround, please add `root` property to each project's `project.json` (don't rely on the generators to create it for you)

you can check this fixed minimal reproduction https://github.com/ronnetzer/nx-github-actions-error (cloned from @robinpellegrims's repro)

Please let me know if this fixed is not working for you @jason-edstrom @tamascsaba @robinpellegrims

**Comment by tamascsaba** [comment]
I have more than 200 `project.json` in my project, so if it easier to update this action to version 14 please let me know.

**Comment by ronnetzer** [comment]
@tamascsaba This is something that can be managed with a simple search & replace, in any case updating to 14 will take time and I can't guarantee that it will be started anytime soon.

Also, there are some issues that block the update, the biggest one is migrating back from github-script action to standalone shell scripts, after that I'll need to do some cleanup of NX internal code I had to overwrite in order to use it in github-script.

I will probably have more time to get into this update after the holidays season in Israel (around November)

**Comment by tamascsaba** [comment]
@ronnetzer thank you very much your informations. I really appreciate your quick feedback 👍

**Comment by ctjhoa** [comment]
For those who don't want to deal with the `root` attribute, I've done a script which add it automatically so your repo can stay clean on latest NX versions.
```yml
  setup:
    runs-on: ubuntu-latest
    name: Affected Matrix
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: fix https://github.com/e-square-io/nx-github-actions/issues/53
        run: >
          addRoot() {
            ROOT_PATH=$(dirname "$1")
            PROJECT_CONTENT=$(jq ". + {root: \"${ROOT_PATH}\"}" < "$1")
            echo "$PROJECT_CONTENT" > "$1"
          };
          find apps -name project.json | while read file; do addRoot "$file"; done;
          find libs -name project.json | while read file; do addRoot "$file"; done;
          find tools -name project.json | while read file; do addRoot "$file"; done;
        shell: bash
      - name: Calculate affected projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'lint,test,build'
          maxDistribution: 3
          checkout: false
```
